### ISSUE TITLE
Capitalize the text of the right-click menu item

### ISSUE THREAD

**Issue by mizhoux** [MaloPolese/copy-json-path#20]
**Is your feature request related to a problem? Please describe.**

Of all the right-click menu items, "Copy json path" looks obtrusive.

![right-click-menu-items](https://github.com/MaloPolese/copy-json-path/assets/15724596/ae471691-1232-4c16-882a-1284d5708bad)

**Describe the solution you'd like**

Please modify the text of the right-click menu item to capitalize it, such as "Copy JSON Path" or "Copy Json Path", so that it is consistent with the text of other menu items.

**Comment by MaloPolese** [comment]
Hello @mizhoux,

Thanks for the suggestion, I will make the change this week 👍

**Comment by mizhoux** [comment]
Looking forward to update 👀
