### ISSUE TITLE
Make JSONtoPath a npm lib

### ISSUE THREAD

**Issue by Xterionix** [MaloPolese/copy-json-path#22]
Not exactly related to the extension but here goes.

**Is your feature request related to a problem? Please describe.**

I've been trying to figure out a good way to get the JSON path from the cursor position and this does it really well. 

**Describe the solution you'd like**

I was hoping if this was made into an npm package then I'd be able to use it.

**Comment by Xterionix** [comment]
I'm open to helping set it up if that's a concern

**Comment by MaloPolese** [comment]
Hello @Xterionix,
Thanks for your idea 😄 but, I'm not sure I understand your point. Can you give me some use cases?

Do you want to extract the function "getJsonPath" into an external npm package? https://github.com/MaloPolese/copy-json-path/blob/f6d00bf3eec54d95a46579d1d6446f2827a2f049/src/json.path.ts#L15

I invite you to check this lib [jsonc-parser](https://www.npmjs.com/package/jsonc-parser)
