### ISSUE TITLE
Key binding

### ISSUE THREAD

**Issue by simplenotezy** [MaloPolese/copy-json-path#24]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to set a keybinding in your `keybindings.json` file

**Describe the solution you'd like**

```json
{
  "key": "",
  "command": "extension.copy-json-path.copy"
}
```

**Comment by MaloPolese** [comment]
Great idea! @simplenotezy  :rocket: 
I invite you to check the PR i made and give me your feedback on the keybinding

**Comment by simplenotezy** [comment]
Apologies for late response here. It looks great. Thanks for adding it so swiftly!
