### ISSUE TITLE
Not working with JSON with Comments - You must be in a json file to execute this command

### ISSUE THREAD

**Issue by Trikenstein** [MaloPolese/copy-json-path#9]
Using Copy Json Path v1.0.4 on [VSCodium 1.77.0](https://vscodium.com/}

The file name is `demo.json` which is guaranteed is a valid JSON file. Syntax highlighting works OK. Collapse/Expand on the gutter works OK.

`Ctrl-Shift-p` , selec "Copy JSON path", then a popup screen appears in the bottom right :+1: 

```
You must be in a json file to execute this command
```

Also right-click on a key within the JSON file doesn't show the menu item "Copy Json path" as in the screenshot shown in the [README.md](https://github.com/MaloPolese/copy-json-path#readme)

**Comment by MaloPolese** [comment]
Thanks for reporting this bug! :smile:  
I take care of finding its origin and fix it but, If you have any idea, do not hesitate to make a PR.

**Comment by MaloPolese** [comment]
@Trikenstein I can't reproduce the bug on version 1.77.0.
I tested on 1.77.0 and on 1.77.1 and it works fine.
Can you give me more context? Maybe some logs or OS info ?

**Comment by Trikenstein** [comment]
Below is the help/about. Can you show how to get the logs?

```
Version: 1.77.0
Release: 23093
Commit: e65f7efc8171cf574d1564b00d34068b92beb954
Date: 2023-04-03T08:47:06.192Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-69-generic
Sandboxed: No
```

**Comment by MaloPolese** [comment]
Hello,

- Maybe give me the result of `uname -a` 
- For the logs:
  - When you go to `Help > Toggle Developer Tools` inside the `Console` tab of the `Developer Tools` is there an error that shows up when you do the `Copy Json Path` action?
![image](https://user-images.githubusercontent.com/37849933/230922808-7617219e-2cb2-4be5-a181-93b907ebb577.png)

  - You can also open a terminal and go to the `Output` tab. In this tab, select `Copy Json Path - Log` from the drop down menu on the top right.
![image](https://user-images.githubusercontent.com/37849933/230922659-c0ff5005-45f5-4c83-ab93-0e0f2cc2f2cf.png)

**Comment by Trikenstein** [comment]
```shell
uname -a 
Linux myComputerName 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```


Toggle Developer Tools, Console:

```
You must be in a json file to execute this command
onDidChangeNotification @ workbench.desktop.main.js:750
(anonymous) @ workbench.desktop.main.js:750
invoke @ workbench.desktop.main.js:86
deliver @ workbench.desktop.main.js:86
fire @ workbench.desktop.main.js:86
addNotification @ workbench.desktop.main.js:750
notify @ workbench.desktop.main.js:1697
(anonymous) @ workbench.desktop.main.js:1592
_showMessage @ workbench.desktop.main.js:1592
$showMessage @ workbench.desktop.main.js:1592
_doInvokeHandler @ workbench.desktop.main.js:1599
_invokeHandler @ workbench.desktop.main.js:1599
_receiveRequest @ workbench.desktop.main.js:1599
_receiveOneMessage @ workbench.desktop.main.js:1599
(anonymous) @ workbench.desktop.main.js:1599
invoke @ workbench.desktop.main.js:86
deliver @ workbench.desktop.main.js:86
fire @ workbench.desktop.main.js:86
fire @ workbench.desktop.main.js:556
_receiveMessage @ workbench.desktop.main.js:556
(anonymous) @ workbench.desktop.main.js:556
invoke @ workbench.desktop.main.js:86
deliver @ workbench.desktop.main.js:86
fire @ workbench.desktop.main.js:86
acceptChunk @ workbench.desktop.main.js:556
(anonymous) @ workbench.desktop.main.js:556
T @ workbench.desktop.main.js:556
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
Show 2 more frames
```

**Comment by MaloPolese** [comment]
Humm, I tested on a virtual machine similar to your system and I can't reproduce this bug...

As it is, I really don't see a solution. You are free to create a PR if you find where the bug comes from
An update of vscodium or of your system could perhaps solve this problem. who knows :thinking: 

Last question. In the bare of vscode on the right, what is the name of the file type in which you want to use the extension ? `Json` or `JSON with Comments` or something else?
![image](https://user-images.githubusercontent.com/37849933/231009890-01c5c7c5-8fc0-42dd-8084-b2c9b1ea734c.png)
![image](https://user-images.githubusercontent.com/37849933/231009921-18ba4364-081a-40be-9ec4-f78403442afe.png)

**Comment by Trikenstein** [comment]
Thanks, working when switching to language mode JSON. 

The file I was testing is a regular JSON output by a command line tool. The filename is `blabla.json`. In the status bar, the language mode was set to `JSON with Comments`. When I switch to `JSON`, the "Copy json path" menu becomes visible in the context menu (right-click on the JSON keyname within the editor). And does copy correctly the JSON path into clipboard.

Would it be OK to improve the `copy-json-path` extension to work with `JSON with Comments` language mode ?

**Comment by MaloPolese** [comment]
When I did the test I saw that the "Json with comment" mode did not work indeed. I wanted your confirmation on this point.

I will add this feature, it's an oversight on my part. Many thanks for your issue.
